package com.hcservice.dao;

import com.hcservice.domain.model.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    Role selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ROLE
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    int updateByPrimaryKey(Role record);
}