package com.hcservice.domain.model;

import lombok.ToString;

import java.util.List;

@ToString
public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.ADMIN_ID
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.ADMIN_NAME
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private String adminName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.EAMIL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private String eamil;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.PASSWORD
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADMIN_INFO.PICTURE_URL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    private String pictureUrl;

    private List<Role> roles;

    public List<Role> getRoles() {
        return roles;
    }

    public void setRoles(List<Role> roles) {
        this.roles = roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.ADMIN_ID
     *
     * @return the value of ADMIN_INFO.ADMIN_ID
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.ADMIN_ID
     *
     * @param adminId the value for ADMIN_INFO.ADMIN_ID
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.ADMIN_NAME
     *
     * @return the value of ADMIN_INFO.ADMIN_NAME
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.ADMIN_NAME
     *
     * @param adminName the value for ADMIN_INFO.ADMIN_NAME
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName == null ? null : adminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.EAMIL
     *
     * @return the value of ADMIN_INFO.EAMIL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public String getEamil() {
        return eamil;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.EAMIL
     *
     * @param eamil the value for ADMIN_INFO.EAMIL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setEamil(String eamil) {
        this.eamil = eamil == null ? null : eamil.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.PHONE_NUMBER
     *
     * @return the value of ADMIN_INFO.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.PHONE_NUMBER
     *
     * @param phoneNumber the value for ADMIN_INFO.PHONE_NUMBER
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.PASSWORD
     *
     * @return the value of ADMIN_INFO.PASSWORD
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.PASSWORD
     *
     * @param password the value for ADMIN_INFO.PASSWORD
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADMIN_INFO.PICTURE_URL
     *
     * @return the value of ADMIN_INFO.PICTURE_URL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public String getPictureUrl() {
        return pictureUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADMIN_INFO.PICTURE_URL
     *
     * @param pictureUrl the value for ADMIN_INFO.PICTURE_URL
     *
     * @mbg.generated Fri Mar 12 22:50:33 GMT+08:00 2021
     */
    public void setPictureUrl(String pictureUrl) {
        this.pictureUrl = pictureUrl == null ? null : pictureUrl.trim();
    }
}